// *Author：jxx
// *Contact：461857658@qq.com
// *代码由框架生成,任何更改都可能导致被代码生成器覆盖
export default function(){
    const table = {
        key: 'ID',
        footer: "Foots",
        cnName: '缺料运算结果',
        name: 'OCP_LackMtrlResult',
        newTabEdit: false,
        url: "/OCP_LackMtrlResult/",
        sortName: "CreateDate"
    };
    const tableName = table.name;
    const tableCNName = table.cnName;
    const newTabEdit = false;
    const key = table.key;
    const editFormFields = {"SOBillNo":"","MtoNo":"","TopMaterialNumber":"","Urgency":"","TopSpecification":"","ProductCategory":"","MaterialNumber":"","MaterialName":"","Specification":"","ErpClsid":"","NeedQty":"","InventoryQty":"","PlanedQty":"","UnPlanedQty":"","BillNo":"","BillType":"","POQty":"","SupplierName":"","PurchaserName":"","PlanStartDate":"","PlanEndDate":"","CGSQAuditDate":"","WWReleaseDate":"","PickMtrlDate":"","StartDate":"","MOCreateDate":"","FinishDate":"","POCreateDate":"","POAuditDate":"","PlanDeliveryDate":"","F_ORA_DATETIME":"","F_BLN_HFJHRQ":"","F_RLRP_CDRQ":""};
    const editFormOptions = [[{"title":"销售单据号","field":"SOBillNo"},
                               {"title":"计划跟踪号","field":"MtoNo"},
                               {"title":"整机物料编码","field":"TopMaterialNumber"}],
                              [{"title":"紧急等级","field":"Urgency"},
                               {"title":"整机规格型号","field":"TopSpecification"}],
                              [{"title":"物料编码","field":"MaterialNumber"},
                               {"title":"物料名称","field":"MaterialName"},
                               {"title":"产品型号","field":"ProductCategory"}],
                              [{"dataKey":"物料属性","data":[],"title":"物料属性","field":"ErpClsid","type":"select","comparationList":[{"key":"select","value":"select"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"规格型号","field":"Specification"},
                               {"title":"需求数量","field":"NeedQty","type":"decimal","comparationList":[{"key":"decimal","value":"decimal"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]}],
                              [{"title":"库存数量","field":"InventoryQty","type":"decimal","comparationList":[{"key":"decimal","value":"decimal"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"已下计划(在途,在制)","field":"PlanedQty","type":"decimal","comparationList":[{"key":"decimal","value":"decimal"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"未下计划数量","field":"UnPlanedQty","type":"decimal","comparationList":[{"key":"decimal","value":"decimal"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]}],
                              [{"title":"单据编号","field":"BillNo"},
                               {"title":"单据分类","field":"BillType"},
                               {"title":"采购数量","field":"POQty","type":"decimal","comparationList":[{"key":"decimal","value":"decimal"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]}],
                              [{"title":"供应商","field":"SupplierName"},
                               {"title":"负责人","field":"PurchaserName"},
                               {"title":"计划开始日期","field":"PlanStartDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]}],
                              [{"title":"计划完成日期","field":"PlanEndDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"采购申请审核日期","field":"CGSQAuditDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"委外订单下达日期","field":"WWReleaseDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]}],
                              [{"title":"领料日期","field":"PickMtrlDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"生产实际开工日期","field":"StartDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"生产订单创建日期","field":"MOCreateDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]}],
                              [{"title":"生产计划完工日期","field":"FinishDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"采购订单创建日期","field":"POCreateDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"采购订单审核日期","field":"POAuditDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]}],
                              [{"title":"计划交货日期","field":"PlanDeliveryDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]}],
                              [{"title":"客户要货日期","field":"F_ORA_DATETIME"},
                               {"title":"销售订单回复交货日期","field":"F_BLN_HFJHRQ"},
                               {"title":"插单日期","field":"F_RLRP_CDRQ"}]];
    const searchFormFields = {"Urgency":"","ProductCategory":"","Specification":"","TopSpecification":"","MaterialNumber":"","MaterialName":"","ErpClsid":[],"BillNo":""};
    const searchFormOptions = [[{"title":"销售合同号","field":"ContractNo","type":"multipleInput"},{"title":"销售单据号","field":"SOBillNo","type":"multipleInput"},{"title":"计划跟踪号","field":"MtoNo","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]},{"title":"整机物料编码","field":"TopMaterialNumber","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]}],[{"title":"紧急等级","field":"Urgency","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]},{"title":"整机规格型号","field":"TopSpecification","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]},{"title":"物料编码","field":"MaterialNumber","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]},{"title":"物料名称","field":"MaterialName","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]}],[{"title":"产品型号","field":"ProductCategory","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]},{"dataKey":"物料属性","data":[],"title":"物料属性","field":"ErpClsid","type":"selectList","comparationList":[{"key":"selectList","value":"select多选"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]},{"title":"规格型号","field":"Specification","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]},{"title":"单据编号","field":"BillNo","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]}]];
    const columns = [{field:'ContractNo',title:'销售合同号',type:'string',sort:true,width:120,align:'left'},
                       {field:'SOBillNo',title:'销售单据号',type:'string',sort:true,width:120,align:'left'},
                       {field:'MtoNo',title:'计划跟踪号',type:'string',sort:true,width:120,align:'left'},
                       {field:'ProScheduleYearMonth',title:'排产月份',type:'string',width:220,align:'left'},
                       {field:'PlanTaskMonth',title:'月度任务',type:'string',sort:true,width:120,align:'left'},
                       {field:'PlanTaskWeek',title:'周任务',type:'string',sort:true,width:120,align:'left'},
                       {field:'Urgency',title:'紧急等级',type:'string',sort:true,width:120,align:'left'},
                       {field:'TopMaterialNumber',title:'整机物料编码',type:'string',sort:true,width:130,align:'left'},
                       {field:'ProductCategory',title:'产品型号',type:'string',sort:true,width:120,align:'left'},
                       {field:'Specification',title:'规格型号',type:'string',sort:true,width:220,align:'left'},
                       {field:'TopSpecification',title:'整机规格型号',type:'string',sort:true,width:220,align:'left'},
                       {field:'MaterialNumber',title:'物料编码',type:'string',sort:true,width:220,align:'left'},
                       {field:'MaterialName',title:'物料名称',type:'string',sort:true,width:220,align:'left'},
                       {field:'ErpClsid',title:'物料属性',type:'string',bind:{ key:'物料属性',data:[]},sort:true,width:110,align:'left'},
                       {field:'MaterialCategory',title:'物料分类',type:'string',width:120,align:'left'},
                       {field:'NeedQty',title:'需求数量',type:'decimal',sort:true,width:110,align:'left'},
                       {field:'InventoryQty',title:'库存数量',type:'decimal',sort:true,width:110,align:'left'},
                       {field:'PlanedQty',title:'已下计划(在途,在制)',type:'decimal',sort:true,width:180,align:'left'},
                       {field:'UnPlanedQty',title:'未下计划数量',type:'decimal',sort:true,width:130,align:'left'},
                       {field:'BillNo',title:'单据编号',type:'string',sort:true,width:110,align:'left'},
                       {field:'BillType',title:'单据分类',type:'string',sort:true,width:120,align:'left'},
                       {field:'POQty',title:'采购数量',type:'decimal',sort:true,width:110,align:'left'},
                       {field:'SupplierName',title:'供应商',type:'string',sort:true,width:120,align:'left'},
                       {field:'PurchaserName',title:'负责人',type:'string',sort:true,width:120,align:'left'},
                       {field:'PlanStartDate',title:'计划开始日期',type:'date',sort:true,width:150,align:'left'},
                       {field:'PlanEndDate',title:'计划完成日期',type:'date',sort:true,width:150,align:'left'},
                       {field:'CGSQAuditDate',title:'采购申请审核日期',type:'date',sort:true,width:160,align:'left'},
                       {field:'WWReleaseDate',title:'委外订单下达日期',type:'date',sort:true,width:160,align:'left'},
                       {field:'PickMtrlDate',title:'领料日期',type:'date',sort:true,width:160,align:'left'},
                       {field:'StartDate',title:'生产实际开工日期',type:'date',sort:true,width:160,align:'left'},
                       {field:'MOCreateDate',title:'生产订单创建日期',type:'date',sort:true,width:160,align:'left'},
                       {field:'FinishDate',title:'生产计划完工日期',type:'date',sort:true,width:160,align:'left'},
                       {field:'POCreateDate',title:'采购订单创建日期',type:'date',sort:true,width:160,align:'left'},
                       {field:'POAuditDate',title:'采购订单审核日期',type:'date',sort:true,width:160,align:'left'},
                       {field:'PlanDeliveryDate',title:'计划交货日期',type:'date',sort:true,width:160,align:'left'},
                       {field:'F_ORA_DATETIME',title:'客户要货日期',type:'datetime',width:150,align:'left'},
                       {field:'F_BLN_HFJHRQ',title:'销售订单回复交货日期',type:'datetime',width:150,align:'left'},
                       {field:'F_RLRP_CDRQ',title:'插单日期',type:'datetime',width:150,align:'left'},
                       {field:'CreateDate',title:'运算时间',type:'datetime',width:150,align:'left'},
                       {field:'Creator',title:'运算人',type:'string',width:100,hidden:true,align:'left'},
                       {field:'ID',title:'主建',type:'long',sort:true,width:80,hidden:true,readonly:true,require:true,align:'left'},
                       {field:'ComputeID',title:'运算ID',type:'long',sort:true,width:80,hidden:true,align:'left'},
                       {field:'CreateID',title:'创建人Id',type:'int',width:80,hidden:true,align:'left'},
                       {field:'Modifier',title:'修改人',type:'string',width:100,hidden:true,align:'left'},
                       {field:'ModifyDate',title:'修改日期',type:'datetime',width:150,hidden:true,align:'left'},
                       {field:'ModifyID',title:'修改人Id',type:'int',width:80,hidden:true,align:'left'},
                       {field:'ESBID',title:'ESB主键',type:'string',width:110,hidden:true,align:'left'},
                       {field:'PlanTaskTime',title:'任务时间',type:'string',width:120,hidden:true,align:'left'},
                       {field:'TopMaterialID',title:'物料ID',type:'long',width:80,hidden:true,align:'left'},
                       {field:'MaterialID',title:'物料ID',type:'long',width:80,hidden:true,align:'left'}];
    const detail ={columns:[]};
    const details = [];

    return {
        table,
        key,
        tableName,
        tableCNName,
        newTabEdit,
        editFormFields,
        editFormOptions,
        searchFormFields,
        searchFormOptions,
        columns,
        detail,
        details
    };
}