// *Author：jxx
// *Contact：461857658@qq.com
// *代码由框架生成,任何更改都可能导致被代码生成器覆盖
export default function(){
    const table = {
        key: 'TrackID',
        footer: "Foots",
        cnName: '采购跟踪',
        name: 'OCP_POUnFinishTrack',
        newTabEdit: false,
        url: "/OCP_POUnFinishTrack/",
        sortName: "CreateDate"
    };
    const tableName = table.name;
    const tableCNName = table.cnName;
    const newTabEdit = false;
    const key = table.key;
    const editFormFields = {"POBillNo":"","FENTRYID":"","PlanTaskMonth":"","PlanTaskWeek":"","Urgency":"","MaterialID":"","MaterialCode":"","MaterialName":"","CGSQCreateDate":"","CGSQAuditDate":"","POCreateDate":"","RequiredDeliveryDate":"","DeliveryNo":"","LatestReplyDeliveryDate":"","LatestDeliveryDate":"","LatestArrivalDate":"","LatestQualityCheckDate":"","LatestInboundDate":"","InboundQty":""};
    const editFormOptions = [[{"title":"采购订单明细ID","field":"FENTRYID"},
                               {"title":"采购订单编号","field":"POBillNo"},
                               {"title":"月度任务","field":"PlanTaskMonth"}],
                              [{"title":"周任务","field":"PlanTaskWeek"},
                               {"title":"紧急等级","field":"Urgency"},
                               {"title":"物料ID","field":"MaterialID"}],
                              [{"title":"物料码","field":"MaterialCode"},
                               {"title":"物料名称","field":"MaterialName"},
                               {"title":"采购申请单创建日期","field":"CGSQCreateDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]}],
                              [{"title":"采购申请单审核日期","field":"CGSQAuditDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"采购订单创建日期","field":"POCreateDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]}],
                              [{"title":"交货日期","field":"RequiredDeliveryDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"送货单号","field":"DeliveryNo"},
                               {"title":"最近回复交货日期","field":"LatestReplyDeliveryDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]}],
                              [{"title":"最近送货日期","field":"LatestDeliveryDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"最近到货日期","field":"LatestArrivalDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"最近质检日期","field":"LatestQualityCheckDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]}],
                              [{"title":"入库数量","field":"InboundQty","type":"decimal","comparationList":[{"key":"decimal","value":"decimal"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]},
                               {"title":"最近入库日期","field":"LatestInboundDate","type":"datetime","comparationList":[{"key":"datetime","value":"datetime(年月日时分秒)"},
                               {"key":"EMPTY","value":"空"},
                               {"key":"NOT_EMPTY","value":"不空"}]}]];
    const searchFormFields = {"MaterialCode":"","PlanTaskMonth":"","PlanTaskWeek":"","Urgency":""};
    const searchFormOptions = [[{"title":"跟踪ID","field":"TrackID"},{"title":"计划跟踪号","field":"PlanTraceNo","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]},{"title":"采购订单明细ID","field":"FENTRYID"},{"title":"采购订单编号","field":"POBillNo","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]}],[{"title":"月度任务","field":"PlanTaskMonth","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]},{"title":"周任务","field":"PlanTaskWeek","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]},{"title":"紧急等级","field":"Urgency","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]},{"title":"物料码","field":"MaterialCode","type":"like","comparationList":[{"key":"like","value":"模糊查询(包含)"},{"key":"EMPTY","value":"空"},{"key":"NOT_EMPTY","value":"不空"}]}]];
    const columns = [{field:'POBillNo',title:'采购订单编号',type:'string',sort:true,width:140,align:'left'},
                       {field:'Seq',title:'行号',type:'int',width:80,align:'left'},
                       {field:'SupplierCode',title:'供应商代码',type:'string',width:120,align:'left'},
                       {field:'SupplierName',title:'供应商名称',type:'string',width:220,align:'left'},
                       {field:'BillStatus',title:'订单状态',type:'string',width:120,align:'left'},
                       {field:'PlanTraceNo',title:'计划跟踪号',type:'string',sort:true,width:120,align:'left'},
                       {field:'MaterialCode',title:'物料码',type:'string',sort:true,width:120,align:'left'},
                       {field:'MaterialName',title:'物料名称',type:'string',sort:true,width:220,align:'left'},
                       {field:'Specification',title:'规格型号',type:'string',width:220,align:'left'},
                       {field:'MaterialCategory',title:'物料分类',type:'string',width:120,align:'left'},
                       {field:'CGSQCreateDate',title:'采购申请单创建日期',type:'date',sort:true,width:170,align:'left'},
                       {field:'CGSQAuditDate',title:'采购申请单审核日期',type:'date',sort:true,width:170,align:'left'},
                       {field:'POCreateDate',title:'采购订单创建日期',type:'date',sort:true,width:160,align:'left'},
                       {field:'POAuditDate',title:'采购订单审核日期',type:'date',width:150,align:'left'},
                       {field:'POQty',title:'采购数量',type:'decimal',width:110,align:'left'},
                       {field:'RequiredDeliveryDate',title:'交货日期',type:'date',sort:true,width:150,align:'left'},
                       {field:'DeliveryNo',title:'送货单号',type:'string',sort:true,width:220,align:'left'},
                       {field:'LatestReplyDeliveryDate',title:'最近回复交货日期',type:'date',sort:true,width:170,align:'left'},
                       {field:'LatestDeliveryDate',title:'最近送货日期',type:'date',sort:true,width:150,align:'left'},
                       {field:'TotalDeliveryQty',title:'累计送货数量',type:'decimal',width:110,align:'left'},
                       {field:'LatestArrivalDate',title:'最近到货日期',type:'date',sort:true,width:150,align:'left'},
                       {field:'TotalArrivalQty',title:'累计到货数量',type:'decimal',width:110,align:'left'},
                       {field:'DeliveryStatus',title:'送货状态',type:'string',width:120,align:'left'},
                       {field:'InspectionStatus',title:'未质检状态',type:'string',width:120,align:'left'},
                       {field:'LatestQualityCheckDate',title:'最近质检日期',type:'date',sort:true,width:150,align:'left'},
                       {field:'TotalQualifiedQty',title:'累计合格数量',type:'decimal',width:110,align:'left'},
                       {field:'PreprocessStatus',title:'前处理状态',type:'string',width:120,align:'left'},
                       {field:'LatestPreprocessDate',title:'最近前处理日期',type:'datetime',width:150,align:'left'},
                       {field:'InstockStatus',title:'入库状态',type:'string',width:120,align:'left'},
                       {field:'LatestInboundDate',title:'最近入库日期',type:'date',sort:true,width:150,align:'left'},
                       {field:'WMSInboundQty',title:'累计入库数量',type:'decimal',width:110,align:'left'},
                       {field:'Remark',title:'备注',type:'string',width:220,align:'left'},
                       {field:'OrderRemark',title:'订单备注',type:'string',width:220,align:'left'},
                       {field:'TrackID',title:'跟踪ID',type:'long',sort:true,width:120,hidden:true,readonly:true,require:true,align:'left'},
                       {field:'FID',title:'采购订单ID',type:'long',sort:true,width:80,hidden:true,align:'left'},
                       {field:'FENTRYID',title:'采购订单明细ID',type:'long',sort:true,width:80,hidden:true,align:'left'},
                       {field:'PlanTaskMonth',title:'月度任务',type:'string',sort:true,width:220,hidden:true,align:'left'},
                       {field:'PlanTaskWeek',title:'周任务',type:'string',sort:true,width:220,hidden:true,align:'left'},
                       {field:'Urgency',title:'紧急等级',type:'string',sort:true,width:220,hidden:true,align:'left'},
                       {field:'MaterialID',title:'物料ID',type:'long',sort:true,width:80,hidden:true,align:'left'},
                       {field:'InboundQty',title:'入库数量',type:'decimal',sort:true,width:110,hidden:true,align:'left'},
                       {field:'CreateID',title:'创建人ID',type:'int',width:80,hidden:true,align:'left'},
                       {field:'CreateDate',title:'创建日期',type:'datetime',width:150,hidden:true,align:'left'},
                       {field:'Creator',title:'创建人',type:'string',width:100,hidden:true,align:'left'},
                       {field:'Modifier',title:'修改人',type:'string',width:100,hidden:true,align:'left'},
                       {field:'ModifyDate',title:'修改日期',type:'datetime',width:150,hidden:true,align:'left'},
                       {field:'ModifyID',title:'修改人ID',type:'int',width:80,hidden:true,align:'left'}];
    const detail ={columns:[]};
    const details = [];

    return {
        table,
        key,
        tableName,
        tableCNName,
        newTabEdit,
        editFormFields,
        editFormOptions,
        searchFormFields,
        searchFormOptions,
        columns,
        detail,
        details
    };
}